### ISSUE TITLE
Setting a path for pytest

### ISSUE THREAD

**Issue by erlebach** [ericsalesdeandrade/pytest-pythonpath-example#1]
I read your article, and have tried setting the path via script and via pytest.ini. Everything works, EXCEPT that pytest prepends the root folder to any path I create. Thus, here is pytest.ini: 
```
[pytest]
pythonpath = /autograder/MAKE-STUDENT-OUTPUT/CODE   ./pytest_utils GORDON
```
and here it the path as printed from a test file: 
```
collecting ... ['/autograder/MAKE-STUDENT-OUTPUT/TEST', '/autograder/MAKE-STUDENT-OUTPUT/CODE', '/autograder/MAKE-STUDENT-OUTPUT/TEST/pytest_utils', '/autograder/MAKE-STUDENT-OUTPUT/TEST/GORDON', '/usr/local/bin', '/usr/lib/python310.zip', '/usr/lib/python3.10', '/usr/lib/python3.10/lib-dynload', '/usr/local/lib/python3.10/dist-packages', '/autograder/git-repo/CAP-5771-s24-grading-1/pytest_utils', '/usr/lib/python3/dist-packages']
```

Why is the folder from  which I am executing pytest the first listed? I want my python path to PREPEND the current folder .../TEST. Is this possible? Because this does not happen on my laptop and does happen on an Ubuntu system, I feel that this behavior is a controllable parameter. Can you please help? 

   Gordon

**Comment by ericsalesdeandrade** [comment]
Hi Gordon, 

Python will always prepend the current folder where it's being run from to the `sys.path` as default. 

However, using Pytest hooks you can modify this behavior - more importantly the `pytest_configure` hook. 

Create a `conftest.py` file in the directory containing the tests. 

```
import sys

def pytest_sessionstart(session):
    print(f"Collecting ... {sys.path}")

def pytest_configure(config):
    desired_path = "DESIRED_PATH_TO_BE_ADDED_TO_PYTHONPATH"
    if desired_path not in sys.path:
        sys.path.insert(0, desired_path)
```

![Screenshot 2024-03-07 at 20 51 05](https://github.com/ericsalesdeandrade/pytest-pythonpath-example/assets/95698321/0bbbb198-c569-42c5-9078-23c6c983c868)

Hope this helps 👍🏼
